# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2017, 10, 4, 23, 1, 39, 151135, tzinfo=utc))),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
    ]
