# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='acc_description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='debit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acc_views.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
