# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_views', '0003_auto_20171004_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
